//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UUB
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int order_id { get; set; }
        public string frist_name { get; set; }
        public string second_name { get; set; }
        public Nullable<int> adress { get; set; }
        public Nullable<int> weight { get; set; }
        public string comment { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<double> cost_value { get; set; }
    }
}
